@startuml

title Delete session

participant TJobExecution
participant EUS
participant EPM
participant Browser

activate Browser
TJobExecution --> EUS: DELETE /session/{sessionId}
EUS --> EPM: delete browser
EPM --> Browser: undeploy
destroy Browser

Browser --> EPM: result
EPM --> EUS: result
EUS --> TJobExecution: result

@enduml