@startuml

title Create session

participant TJobExecution
participant EUS
participant EPM
participant Browser

TJobExecution --> EUS: POST /session
EUS --> EPM: create browser
EPM --> Browser: deploy
activate Browser

Browser --> EPM: result
EPM --> EUS: result
EUS --> TJobExecution: sessionId

@enduml