@startuml

skinparam component {
    FontSize 16
    FontStyle bold
    FontColor white
    BackgroundColor #ffac2f
    ArrowFontColor #333333
    ArrowThickness 2
}
skinparam defaultTextAlignment center
skinparam linetype polyline

package host {
    [TJobExec\nContainer] -- Docker
    [Internal Sut\nContainer(s)] -- Docker
    [Internal Browser\nContainer] -- Docker
    Docker --> TCP

    [Internal Browser\nSession console] --> HTTP

    [Internal Sut\n In Container(s)] -- [Filebeat]
    [Filebeat] --> Beats

    Docker -- [Dockbeat]
    [Dockbeat] --> Beats


    TCP -down- [Logstash]
    Beats -left- [Logstash]
    HTTP -- [Logstash]

    [Logstash] --> [Elasticsearch]
    [Logstash] --> [RabbitMQ]

}

package ExternalSutHost {
    [External\nFilebeat] --> Beats
    [External\nMetricbeat] --> Beats
}


@enduml