@startuml

skinparam participant {
    FontSize 16
    FontStyle bold
    FontColor white
    BackgroundColor #ffac2f
    ArrowFontColor #333333
    ArrowThickness 2
}

' Participants

actor Tester
participant ETM
participant EPM
participant SUT
participant TJobExecution

' Notes over participants
note over EPM
   Deploy components of a TJob
   on Docker or K8s
end note

' Relations

Tester --> ETM: Execute TJob
ETM --> EPM: Request SuT

create SUT
EPM --> SUT: Deploy
activate SUT

ETM --> EPM: Request TJobExecution
create TJobExecution
EPM --> TJobExecution: deploy
activate TJobExecution

group Test Execution
    TJobExecution --> ETM: logs/metrics
    ETM --> Tester: logs/metrics
    TJobExecution --> SUT: exercise

    SUT --> ETM: logs/metrics
    ETM --> Tester: logs/metrics

    TJobExecution --> SUT: verify behavior
end

TJobExecution --> ETM: Test results
destroy TJobExecution
destroy SUT
ETM --> Tester: Test results



@enduml